name: Pipeline Despliege de imagen en ECS

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Construir y Deploy para ECS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'false'

    - name: Construir imagen docker
      run: docker build -t 515966540576.dkr.ecr.us-east-1.amazonaws.com/pruebadevops:latest .

    - name: Push imagen a ECR
      run: docker push 515966540576.dkr.ecr.us-east-1.amazonaws.com/pruebadevops:latest

    - name: Actualizar imagen nueva a ECS
      run: |
        aws ecs update-service \
          --cluster ${{ vars.ECS_CLUSTER }} \
          --service ${{ vars.ECS_SERVICE }} \
          --force-new-deployment \
          --region ${{ vars.AWS_REGION }}